-- CREATE TABLE MATERIAL (
--     MATERIAL_ID INT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY
-- );

-- CREATE TABLE MATIRIAL_NAME (
--   MATERIAL_ID INT,
--   LANGUAGE_CODE VARCHAR(10),
--   NAME VARCHAR(30),
  
--   CONSTRAINT FK_MATERIAL_NAME
--         FOREIGN KEY (MATERIAL_ID)
--         REFERENCES MATERIAL(MATERIAL_ID)
--         ON DELETE CASCADE  -- 当主表记录删除时，自动删除从表记录
--         ON UPDATE CASCADE, -- 当主表主键更新时，同步更新从表外键

--   CONSTRAINT FK_MATERIAL_LANGUAGE
--         FOREIGN KEY (LANGUAGE_CODE)
--         REFERENCES LANGUAGE(LANGUAGE_CODE)
--         ON DELETE RESTRICT  -- 防止删除正在使用的语言
--         ON UPDATE CASCADE,

  
--     CONSTRAINT unq_material_language 
--         UNIQUE (MATERIAL_ID, LANGUAGE_CODE)
-- )


-- CREATE TABLE CATEGORY (
--     CATEGORY_ID INT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY
-- );

CREATE TABLE CATEGORY_NAME (
  CATEGORY_ID INT,
  LANGUAGE_CODE VARCHAR(10),
  NAME VARCHAR(30),
  
  CONSTRAINT FK_CATEGORY_NAME
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID)
        ON DELETE CASCADE  -- 当主表记录删除时，自动删除从表记录
        ON UPDATE CASCADE, -- 当主表主键更新时，同步更新从表外键

  CONSTRAINT FK_CATEGORY_LANGUAGE
        FOREIGN KEY (LANGUAGE_CODE)
        REFERENCES LANGUAGE(LANGUAGE_CODE)
        ON DELETE RESTRICT  -- 防止删除正在使用的语言
        ON UPDATE CASCADE,

    CONSTRAINT UNQ_CATEGORY_LANGUAGE
        UNIQUE (CATEGORY_ID, LANGUAGE_CODE)
)

CREATE TABLE PRODUCT(
  PRODUCT_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ITEM_CODE VARCHAR(20) NOT NULL,
  CATEGORY_ID INT NOT NULL,
  BLADE_MATERIAL_ID INT NOT NULL,
  FITTINGS_MATRERIAL_ID INT NOT NULL,
  TOTAL_LENGTH NUMERIC(6,2) NOT NULL,
  BLADE_LENGTH NUMERIC(6,2) NOT NULL,
  TSUKA_LENGTH NUMERIC(6,2) NOT NULL,

  
  CONSTRAINT FK_PRODUCT_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY(CATEGORY_ID)
        ON DELETE RESTRICT  -- 当主表记录删除时，自动删除从表记录
        ON UPDATE RESTRICT, -- 当主表主键更新时，同步更新从表外键
  
  CONSTRAINT FK_BLADE_MATERIAL
        FOREIGN KEY (BLADE_MATERIAL_ID)
        REFERENCES MATERIAL(MATERIAL_ID)
        ON DELETE RESTRICT  -- 当主表记录删除时，自动删除从表记录
        ON UPDATE RESTRICT, -- 当主表主键更新时，同步更新从表外键
  
  CONSTRAINT FK_FITTINGS_MATERIAL
        FOREIGN KEY (FITTINGS_MATRERIAL_ID)
        REFERENCES MATERIAL(MATERIAL_ID)
        ON DELETE RESTRICT  -- 当主表记录删除时，自动删除从表记录
        ON UPDATE RESTRICT  -- 当主表主键更新时，同步更新从表外键
)

-- 价格
CREATE TABLE PRICE (
  PRICE_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PRODUCT_ID INT,
  TIER VARCHAR(6),
  VALUE NUMERIC(6,2),

  
  CONSTRAINT chk_tier CHECK (
      tier IN ('10-50', '50-100', '100+')
  ),

  
  CONSTRAINT FK_PRODUCT_PRICE
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCT(PRODUCT_ID)
        ON DELETE RESTRICT  -- 当主表记录删除时，自动删除从表记录
        ON UPDATE RESTRICT  -- 当主表主键更新时，同步更新从表外键
)

-- 用户
CREATE TABLE USER_INFO (
  USER_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMAIL_ADDRESS VARCHAR(30) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  PERMISSION VARCHAR(10) NOT NULL,

  
  CONSTRAINT chk_user_permission CHECK (
      PERMISSION IN ('admin', 'buyer')
  )
  
)

-- 图片

CREATE TABLE IMAGE (
    IMAGE_ID INT GENERATED ALWAYS AS IDENTITY,
    PRODUCT_ID INT NOT NULL,
    URL VARCHAR(255) NOT NULL,
    ORDER_NUMBER INT NOT NULL,
    PRIMARY KEY (IMAGE_ID),
    CONSTRAINT FK_PRODUCT_IMAGE
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)


CREATE TABLE DESCRIPTION (
   DESCRIPTION_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   PRODUCT_ID INT NOT NULL,
   LANGUAGE_CODE VARCHAR(10) NOT NULL,
   CONTENT TEXT NOT NULL,
   CONSTRAINT FK_DESCRIPTION_LANGUAGE
       FOREIGN KEY (LANGUAGE_CODE) REFERENCES LANGUAGE(LANGUAGE_CODE),
  
   CONSTRAINT FK_DESCRIPTION_PRODUCT
       FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)